### ISSUE TITLE
Add to stackage nightly.

### ISSUE THREAD

**Issue by olynch** [diagrams/palette#6]
Currently version 0.3 is not on Stackage nightly because it is manually excluded in build constraints. I just checked and it builds with the latest stackage nightly, so could you please send a pull request to have it re-enabled? Thank you.

**Comment by byorgey** [comment]
Thanks for the nudge.  I've opened a PR adding not just `palette` but a bunch of other packages as well: https://github.com/commercialhaskell/stackage/pull/3688

**Comment by byorgey** [comment]
Yup, it's merged now!

**Comment by olynch** [comment]
Palette is still not in stackage because of https://github.com/commercialhaskell/stackage/blob/b43b5c13e688a6e1f86e15eeabab0fa1aeabeabf/build-constraints.yaml#L1271. Can you send a pull request for this or should I try and bug Jeffrey?

**Comment by byorgey** [comment]
Looks like @jeffreyrosenbluth 's PR is merged now, thanks!
